### ISSUE TITLE
I think you should use flatMap in this line, too. At least that fixed a bug for me.

### ISSUE THREAD

**Issue by skanne** [okwolf/hyperapp-playground#1]
https://github.com/okwolf/hyperapp-playground/blob/8ef3713a84c4488423d65a80cdbb6e206d524ef0/src/html.js#L13

**Comment by okwolf** [comment]
You're right, and I missed one more case for deeply nested HTML calls: https://github.com/okwolf/hyperapp-playground/commit/ee4eef5e4121cdabe44e2f9d851935abc7266cbc
